{{- if and (include "wazuh-operator.installOperator" .) .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wazuh-operator.roleBindingName" . }}
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wazuh-operator.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "wazuh-operator.serviceAccountName" . }}
  namespace: {{ include "wazuh-operator.namespace" . }}
{{- end }}
