{{- if and (include "wazuh-operator.installOperator" .) .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wazuh-operator.serviceAccountName" . }}
  namespace: {{ include "wazuh-operator.namespace" . }}
  labels:
    {{- include "wazuh-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
