{{- if and .Values.secrets.wazuhApi .Values.secrets.wazuhApi.username .Values.secrets.wazuhApi.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.wazuhApi.username | quote }}
  password: {{ .Values.secrets.wazuhApi.password | quote }}
{{- end }}

{{- if and .Values.secrets.indexerAdmin .Values.secrets.indexerAdmin.username .Values.secrets.indexerAdmin.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indexer-admin-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.secrets.indexerAdmin.username | quote }}
  admin-password: {{ .Values.secrets.indexerAdmin.password | quote }}
{{- end }}

{{- if .Values.secrets.wazuhAuthd.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wazuh-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  authd.pass: {{ .Values.secrets.wazuhAuthd.password | quote }}
{{- end }}
